# Generated by Django 4.2.7 on 2023-11-20 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projectinternal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailMainPower',
            fields=[
                ('id_role', models.AutoField(primary_key=True, serialize=False)),
                ('man_days_rate', models.IntegerField(blank=True, null=True)),
                ('man_power', models.IntegerField(blank=True, null=True)),
                ('days', models.IntegerField(blank=True, null=True)),
                ('role', models.TextField(blank=True, null=True)),
                ('id_project', models.ForeignKey(blank=True, db_column='id_project', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='projectinternal.projectinternal')),
            ],
        ),
    ]
