# Generated by Django 4.2.7 on 2023-11-23 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detailmanpower', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataKaryawan',
            fields=[
                ('id_karyawan', models.AutoField(primary_key=True, serialize=False)),
                ('nama_karyawan', models.CharField(max_length=255)),
                ('jabatan', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('profile', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'data_karyawan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectInternal',
            fields=[
                ('id_project', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'project_internal',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='detailmainpower',
            options={'managed': False},
        ),
    ]
