# Generated by Django 4.2.7 on 2023-12-08 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detailmanpower', '0002_datakaryawan_projectinternal_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataKaryawan',
        ),
        migrations.DeleteModel(
            name='ProjectInternal',
        ),
        migrations.AlterModelTable(
            name='detailmainpower',
            table='detail_main_power',
        ),
    ]
