# Generated by Django 4.2.7 on 2023-12-08 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Responsibility',
            fields=[
                ('pm_responsibility', models.CharField(blank=True, max_length=255, null=True)),
                ('project_value', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('id_responsibility', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'responsibility',
                'managed': False,
            },
        ),
    ]
