# Generated by Django 4.2.7 on 2023-11-20 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInternal',
            fields=[
                ('id_project', models.AutoField(primary_key=True, serialize=False)),
                ('requester', models.CharField(blank=True, max_length=100, null=True)),
                ('application_name', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('man_power', models.IntegerField(blank=True, null=True)),
                ('sequence_number', models.CharField(blank=True, max_length=50, null=True)),
                ('hld', models.CharField(blank=True, max_length=255, null=True)),
                ('lld', models.CharField(blank=True, max_length=255, null=True)),
                ('brd', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
