# Generated by Django 4.2.7 on 2023-11-21 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectinternal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectinternal',
            options={'managed': False},
        ),
    ]
