# Generated by Django 4.2.7 on 2023-11-21 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectinternal', '0002_alter_projectinternal_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='projectinternal',
            table='project_internal',
        ),
    ]
