# Generated by Django 4.2.7 on 2023-12-08 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Approvedby',
            fields=[
                ('nama', models.CharField(blank=True, max_length=255, null=True)),
                ('cc_to', models.CharField(blank=True, max_length=255, null=True)),
                ('tanggal', models.DateField(blank=True, null=True)),
                ('id_approv', models.AutoField(primary_key=True, serialize=False)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'approvedBy',
                'managed': False,
            },
        ),
    ]
