# Generated by Django 4.2.7 on 2023-11-20 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detailmanpower', '0001_initial'),
        ('karyawan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataKaryawan',
            fields=[
                ('id_karyawan', models.AutoField(primary_key=True, serialize=False)),
                ('nama_karyawan', models.CharField(max_length=255)),
                ('jabatan', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('id_role', models.ForeignKey(blank=True, db_column='id_role', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='detailmanpower.detailmainpower')),
            ],
        ),
        migrations.DeleteModel(
            name='Karyawan',
        ),
    ]
