# Generated by Django 4.2.7 on 2023-11-20 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karyawan', '0002_datakaryawan_delete_karyawan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datakaryawan',
            name='id_role',
        ),
        migrations.AddField(
            model_name='datakaryawan',
            name='profile',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
