# Generated by Django 4.2.7 on 2023-11-20 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karyawan', '0003_remove_datakaryawan_id_role_datakaryawan_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datakaryawan',
            options={'managed': False},
        ),
    ]
