# Generated by Django 4.2.7 on 2023-11-21 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karyawan', '0004_alter_datakaryawan_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='datakaryawan',
            table='data_karyawan',
        ),
    ]
