# Generated by Django 4.2.7 on 2023-12-20 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetailTimeline',
            fields=[
                ('id_detail_timeline', models.AutoField(primary_key=True, serialize=False)),
                ('weeks', models.IntegerField(blank=True, null=True)),
                ('activity', models.CharField(blank=True, max_length=255, null=True)),
                ('createdat', models.DateTimeField(auto_now_add=True, db_column='createdAt', null=True)),
                ('updateat', models.DateTimeField(auto_now=True, db_column='updateAt', null=True)),
            ],
            options={
                'db_table': 'detail_timeline',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectInternal',
            fields=[
                ('id_project', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('on_going', 'Ongoing'), ('dropped', 'Dropped'), ('finish', 'Finish')], default='on_going', max_length=20)),
                ('requester', models.CharField(blank=True, max_length=100, null=True)),
                ('application_name', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('hld', models.FileField(blank=True, max_length=255, null=True, upload_to='hld/')),
                ('lld', models.FileField(blank=True, max_length=255, null=True, upload_to='lld/')),
                ('brd', models.URLField(blank=True, max_length=255, null=True)),
                ('jumlah_io', models.IntegerField(blank=True, null=True)),
                ('sequence_number', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'project_internal',
                'managed': False,
            },
        ),
    ]
