# Generated by Django 4.2.7 on 2023-12-08 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCharter',
            fields=[
                ('project_name', models.CharField(blank=True, max_length=50, null=True)),
                ('iwo', models.CharField(blank=True, max_length=50, null=True)),
                ('project_manager', models.CharField(blank=True, max_length=50, null=True)),
                ('customer', models.CharField(blank=True, max_length=50, null=True)),
                ('end_customer', models.CharField(blank=True, max_length=50, null=True)),
                ('bu_delivery', models.CharField(blank=True, max_length=50, null=True)),
                ('bu_related', models.CharField(blank=True, max_length=50, null=True)),
                ('id_charter', models.AutoField(primary_key=True, serialize=False)),
                ('project_description', models.CharField(blank=True, max_length=255, null=True)),
                ('jumlah_pc', models.IntegerField(blank=True, null=True)),
                ('status_project', models.TextField(blank=True, default='draft', editable=False, null=True)),
                ('createdat', models.DateTimeField(auto_now_add=True, db_column='createdAt', null=True)),
            ],
            options={
                'db_table': 'project_charter',
                'managed': False,
            },
        ),
    ]
